//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehiculosITM.Models
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;

    public partial class Vehiculo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehiculo()
        {
            this.Ventas = new HashSet<Venta>();
        }
    
        public int id_vehiculo { get; set; }
        public int id_marca { get; set; }
        public string modelo { get; set; }
        public int cantidad_unidades { get; set; }
        public string motor { get; set; }
        public Nullable<int> numero_puertas { get; set; }
        public string tipo_combustible { get; set; }
        public string accesorios { get; set; }
        public decimal precio { get; set; }

        [JsonIgnore]
        public virtual Marca Marca { get; set; }
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Venta> Ventas { get; set; }
    }
}
