//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehiculosITM.Models
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;

    public partial class Venta
    {
        public int id_venta { get; set; }
        public int id_agencia { get; set; }
        public int id_cliente { get; set; }
        public int id_vehiculo { get; set; }
        public System.DateTime fecha_venta { get; set; }
        public decimal total { get; set; }

        [JsonIgnore]
        public virtual Agencia Agencia { get; set; }
        [JsonIgnore]
        public virtual Cliente Cliente { get; set; }
        [JsonIgnore]
        public virtual Vehiculo Vehiculo { get; set; }
    }
}
